export const types = {
  IS_LOADING: 'IS_LOADING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  SET_ERRORS: 'SET_ERRORS',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  OPEN_LOADER: 'OPEN_LOADER',
  CLOSE_LOADER: 'OPEN_LOADER'
};
