import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import moment from 'moment';
import CloseSharpIcon from '@mui/icons-material/CloseSharp';
import AccessTimeRoundedIcon from '@mui/icons-material/AccessTimeRounded';
import Snackbar from '@mui/material/Snackbar';

const Bookings = () => {
  const [isAuth, setIsAuth] = useState(false);
  const router = useRouter();
  const [date, setDate] = useState('');
  const [time, setTime] = useState('');
  const [newTime, setNewTime] = useState('');
  useEffect(() => {
    const dateData = localStorage.getItem('date');
    const day = dateData !== null ? moment(dateData).format('dddd') : '';
    const date =
      dateData !== null ? moment(dateData).format('MMM Do YYYY') : '';
    const timeData = localStorage.getItem('time');
    const newTime = timeData !== null ? timeData : '';
    setDate(`${day}, ${date}`);
    setTime(`${newTime.split(' ')[0]}`);
    if (timeData !== null) {
      setNewTime(
        `${newTime.split(':')[0]}:${
          Number(newTime.split(':')[1].split(' ')[0]) + 15
        }`
      );
    }
  });
  useEffect(() => {
    const checkToken = localStorage.getItem('access_token');
    if (checkToken === null) {
      router.push('/login');
    }
    setIsAuth(true);
  }, [isAuth]);

  return (
    <div className="flex flex-row items-start justify-between">
      <Head>
        <title>Bookings | Cal.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-[100%] bg-secondary p-12 flex flex-col">
        <div className="flex flex-col items-start justify-center">
          <span className="text-base font-bold">Bookings</span>
          <span className="text-gray-500">
            See upcoming and past events booked through your event type links.
          </span>
        </div>
        <div className="flex flex-row items-center w-full my-5">
          <ul className="flex flex-row items-center">
            <li className="mr-5">
              <a href="#">Upcoming</a>
            </li>
            <li className="mx-5">
              <a href="#">Past</a>
            </li>
            <li className="mx-5">
              <a href="#">Cancelled</a>
            </li>
          </ul>
        </div>
        <div className="w-full h-px bg-primary" />
        <div className="flex flex-row items-center justify-between w-full px-5 py-5 mt-10 bg-white border-2 border-secondary">
          <div className="flex flex-col justify-between cursor-pointer">
            <div className="flex flex-row my-2 text-xs">
              <span className="font-bold">{date}</span>
              <span className="ml-3 font-semibold">
                Secret Meeting between Jean Francois and Kalisa John
              </span>
            </div>
            <div className="flex flex-row items-center justify-start my-2 text-xs">
              <span className="ml-1 mr-3 text-gray-300">{time}-</span>

              <span className="ml-1 text-gray-300">{newTime}</span>
            </div>
          </div>
          <div className="flex flex-row justify-between">
            <a
              target="_blank"
              href="/jeanfrancois360/15min"
              className="flex items-center justify-center px-3 py-2 mx-5 border-2 border-secondary"
            >
              <CloseSharpIcon width={15} height={15} className="mr-2" /> Cancel
            </a>
            <button
              type="button"
              className="flex items-center justify-center px-3 py-2 mx-5 border-2 border-secondary"
            >
              <AccessTimeRoundedIcon width={15} height={15} className="mr-2" />
              Reschedule
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Bookings;
